environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: pypy
  - TOXENV: pypy3

install:
  - echo Installed Pythons
  - dir c:\Python*
  - C:\Python36\python -m pip install --upgrade --pre tox

build: false

test_script:
  - C:\Python36\python -m tox
